### PR TITLE
Fix twcc has chance to miss for firefox simulcast rtx

### PR DESCRIPTION
**Pull request by cnderrauber**
When the publisher's offer contains both rid and ssrc-group for simulcast streams, pion will ignore ssrc-group attr and rely on rid in rtp packet to probe rtx stream, since the rtx buffer will forward all packets to the primary buffer once the rtx pair is found, so if we create rtx pair from sdp too early and rtx probing packet arrives after primary packet it will cause the rtx buffer's read method can't return packet to pion then the probing failed and no stream created for the rtx stream, then the twcc extension will not be processed for the rtx stream since the ext id is set after rtx stream created, the result is the bandwidth estimation can't get expected result then quality degraded.
Two conditions are required for the issue: both rid and ssrc-group contains in sdp, rtx probing packet arrives after primary packet. The latter happens randomly so a local dev repro might fail in local env.

### CODE REVIEW

**Review by boks1971 — COMMENTED** [review]
Is there a case of SVC using `rid`? I have seen VP9 SVC have a `rid` of `f`. Would that also be probed in Pion?

@lherman-cs mentioned about SVC probing here in this PR - https://github.com/livekit/livekit/pull/2599

**Review by boks1971 — APPROVED** [review]

**Comment by cnderrauber** [comment]
> Is there a case of SVC using `rid`? I have seen VP9 SVC have a `rid` of `f`. Would that also be probed in Pion?
> 
> @lherman-cs mentioned about SVC probing here in this PR - #2599

It is possible that svc contains `rid` in sdp, but firefox doesn't support it (chrome/safari doesn't contain `ssrc-group` in simulcast/svc sdp)

**Comment by lherman-cs** [comment]
> > Is there a case of SVC using `rid`? I have seen VP9 SVC have a `rid` of `f`. Would that also be probed in Pion?
> > @lherman-cs mentioned about SVC probing here in this PR - #2599
> 
> It is possible that svc contains `rid` in sdp, but firefox doesn't support it (chrome/safari doesn't contain `ssrc-group` in simulcast/svc sdp)

I might be missing something. How do we know if Firefox doesn't support RID? 

I see both RID and ssrc-group in Firefox SDP.

[sender-firefox.txt](https://github.com/livekit/livekit/files/14789629/sender-firefox.txt)

**Review by lherman-cs — APPROVED** [review]

**Review by davidzhao — APPROVED** [review]
👍

**Pull request merged**
