### PR TITLE
Support track level stereo and red setting

### PR DESCRIPTION
**Pull request by cnderrauber**

### CODE REVIEW

**Comment by cnderrauber** [comment]
Fix #970

**Review by davidzhao — APPROVED** [review]
lg,

unrelated to this PR. I see we use `GetLastUnmatchedMediaForOffer` to apply track-specific settings to the SDP. Would this work if multiple tracks of the same type are published in the same offer?

**Comment by cnderrauber** [comment]
> lg,
> 
> unrelated to this PR. I see we use `GetLastUnmatchedMediaForOffer` to apply track-specific settings to the SDP. Would this work if multiple tracks of the same type are published in the same offer?

This func makes a assumption that client publish only one track for each type in every offer, it is a error after checked client sdk, so we need change it to `GetAllUnmatchedMediaFromOffer` in that case

**Comment by davidzhao** [comment]
> This func makes a assumption that client publish only one track for each type in every offer, it is a error after checked client sdk, so we need change it to `GetAllUnmatchedMediaFromOffer` in that case

It's probably a rare case for two tracks of the same type in a single offer.. but it's still possible. The client would debounce offers to bundle them together.. that probably exposes this issue.

**Pull request merged**
