### PR TITLE
Revert "Update pion deps"

### PR DESCRIPTION
**Pull request by boks1971**
Reverts livekit/livekit#2587

### CODE REVIEW

**Review by paulwe — APPROVED** [review]

**Review by davidzhao — APPROVED** [review]

**Comment by boks1971** [comment]
> @Sean-Der pulling in the Pion updates appears to break Go publishers.

Actually, it seems to be affect the subscriber peer connection. The subscriber peer connection got to `connected`, but data channels did not open and Go SDK participant never got to `ACTIVE` state.

**Comment by Sean-Der** [comment]
@boks1971 Do you have an easy way I can reproduce/try locally? If I can see the logs I can figure it out

**Comment by boks1971** [comment]
@Sean-Der I just run server like
```
LIVEKIT_KEYS="<key>: <secret>" ./bin/livekit-server --dev
```
and run `livekit-cli` like
```
./bin/livekit-cli join-room --room myroom --identity bot --api-key <key> --api-secret <secret>
```
That gets stuck when subscriber peer connection says `connected`. We open data channels after that. Looks like it is not even trying to open data channel on server side. So, it could be something in server code that is stuck and not proceeding. On the `livekit-cli` side, you will see that the client is kicked out by server after a minute (JOIN_TIMEOUT hits).

**Comment by Sean-Der** [comment]
Nice! I will come back with an answer ASAP, working on this now.

**Comment by boks1971** [comment]
I will dig further too.

**Comment by Sean-Der** [comment]
Using `livekit-cli` @ 1.3.2 
and `livekit` @ 860702e9dcf93701931e7caee9ec3cd78409a757

I am not able to reproduce yet. What livekit-cli are you using?

**Comment by boks1971** [comment]
I usually build `livekit-cli`. But, some tests are failing even with the revert. So, there is still something else. Will dig further. Than you Sean. Will keep you posted.

**Comment by Sean-Der** [comment]
👍 tell me what I can do to help.

I just tried `livekit-cli` @ https://github.com/livekit/livekit-cli/commit/a5a780e045afb43afb802962136488ffa5e9b7b9 and still seems to be working

**Pull request merged**
