### PR TITLE
Added Xiaomi 2201117TI to devices that does not support H.264

### PR DESCRIPTION
**Pull request by davidzhao**

### CODE REVIEW

**Review by boks1971 — APPROVED** [review]

**Comment by davidzhao** [comment]
some additional concerns with this approach.

@davidliu, I believe the original issue is with publishing, but what about subscribe? Could this device decode a H.264 stream sent by another party?

The current change / device configuration will effectively disable downstream negotiation too. I think in some cases, we'd want to disable publishing of a certain codec (due to hw encoder issues), but we do not want to disable negotiating that codec on the subscriber side (since the tracks are already encoded as such)

**Review by cnderrauber — APPROVED** [review]

**Comment by davidliu** [comment]
AFAIK, these devices can decode H264 fine, it's specifically when trying to simulcast encode H264.

**Comment by cnderrauber** [comment]
Sounds like we need separate publish/subscribe directions from `DisabledCodecs`, and in most case we only need control publish direction as hw decoder works more reliable than encoder, also webrtc has software decoder fallback .

**Comment by davidzhao** [comment]
@cnderrauber @boks1971 I've split publish and subscribe control for disabled codecs, lmk if this works better.

**Comment by cnderrauber** [comment]
It works for me, in most cases we only need set Disabled.Publish

**Pull request merged**
