### PR TITLE
Improve robustness of JoinResponse and ParticipantUpdate race handling

### PR DESCRIPTION
**Pull request by davidzhao**

### CODE REVIEW

**Review by cnderrauber — APPROVED** [review]

**Review by boks1971 — APPROVED** [review]
Not related to this PR, but I just noticed that `VerifySubscribeParticipantInfo` access the `updateCache` without holding a read lock. Can you please add it?

**Comment by boks1971** [comment]
Code placement suggestion. In `participant.go`, might be useful to place `updateLock` along with `updateCache` (and the new `queuedUpdates`) to indicate that those use the same lock. It is only a convention and still does not avoid errors, but when looking to make a change in those areas, it is easier to see that a separate lock is used (ideally, a set of data under the same lock can be made into a separate struct/module so that it is very clear, but that could lead to fragmentation)

**Comment by davidzhao** [comment]
> Not related to this PR, but I just noticed that `VerifySubscribeParticipantInfo` access the `updateCache` without holding a read lock. Can you please add it?

I think that access should be fine, since it's an LRU that'll only skip it if it isn't there.. it's ok if goes into `SendParticipantUpdate`, which will lock the cache and check again.

**Comment by davidzhao** [comment]
> Code placement suggestion. In `participant.go`, might be useful to place `updateLock` along with `updateCache` (and the new `queuedUpdates`) to indicate that those use the same lock. It is only a convention and still does not avoid errors, but when looking to make a change in those areas, it is easier to see that a separate lock is used (ideally, a set of data under the same lock can be made into a separate struct/module so that it is very clear, but that could lead to fragmentation)

Yeah it's not very clear right now. I moved them closer together.. can look at further refactoring later.

**Pull request merged**
