### PR TITLE
Some optimisations in the forwarding path.

### PR DESCRIPTION
**Pull request by boks1971**
NOTE: Not planning to merge for this round of deploy. Wanted to get feedback and then merge for next round possibly if there is value.

Been hard to see changes in CPU usage during a load test as it jumps around, but profiling shows about 7 - 8% improvement. Will do more measurements too.

Changes include
- getting rid of small allocations (in sequencer, while marshalling codec header, generating translation parameters)
- remove call back from pacer. It is okay to run the post packet stuff. There is usually no error from pacer packet send. Even if it is there, the after packet actions are okay to run synchronously.
- do pool release in pacer.

### CODE REVIEW

**Review by cnderrauber — APPROVED** [review]
Looks good! I can compare this with the current version once it is merged.

**Comment by boks1971** [comment]
> Looks good! I can compare this with the current version once it is merged.

Thank you @cnderrauber . Will ping you once I merge this.

**Review by paulwe — APPROVED** [review]

**Review by davidzhao — APPROVED** [review]
nice!

**Review by cnderrauber — APPROVED** [review]
Looks good!

**Pull request merged**
