### PR TITLE
Implement Agents protocol addition

### PR DESCRIPTION
**Pull request by biglittlebigben**
- Allow specifying what agents namespace should be used when starting a room instead of dispatching to all registered namespaces. This also simplifies the agents discovery code.
- Remove the Job object, use the protocol Job object instead
- Rename JobDescription to JobRequest
- Add support for RoomConfiguration to group default agents and other room settings under a preset.
- Store JobDefinitions associated with a room in the RoomInternal object. This allows starting Publisher Jobs as new participants join.

### CODE REVIEW

**Comment by biglittlebigben** [comment]
Status: dispatch of ROOM jobs doesn't seem to work even if agent seems to register properly

**Review by frostbyte73 — APPROVED** [review]
lgtm. How will this work with shared/public agents?

**Comment by paulwe** [comment]
the cloud implementation is different. i don't think this has to support shared agents?

**Comment by biglittlebigben** [comment]
> the cloud implementation is different. i don't think this has to support shared agents?

No shared agents here. I don't think they would make sense for OSS?

**Pull request merged**
