### PR TITLE
distribute load to agents probabilistically, inversely proportionate to load

### PR DESCRIPTION
**Pull request by real-danm**

### CODE REVIEW

**Review by davidzhao — COMMENTED** [review]
I think load balancing needs a bit of work.. but I don't think we'd want to load on the least loaded worker.

this workload is similar to Egress, where we'd ideally want to concentrate work on the top N% of the *most* loaded (but still available) workers.

**Comment by real-danm** [comment]
> I think load balancing needs a bit of work.. but I don't think we'd want to load on the least loaded worker.
> 
> this workload is similar to Egress, where we'd ideally want to concentrate work on the top N% of the _most_ loaded (but still available) workers.

one problem here is that agents by default are only updating their availability every 10s so a burst of jobs could overload the selected worker pretty quickly.
https://github.com/livekit/agents/blob/main/livekit-agents/livekit/agents/worker.py#L41

If efficient packing is the goal, maybe decreasing the worker update interval is a better approach for now?

**Comment by davidzhao** [comment]
> one problem here is that agents by default are only updating their availability every 10s so a burst of jobs could overload the selected worker pretty quickly. https://github.com/livekit/agents/blob/main/livekit-agents/livekit/agents/worker.py#L41
> 
> If efficient packing is the goal, maybe decreasing the worker update interval is a better approach for now?

you are right that we should probably not make efficient packing a goal. with that in mind I think your approach is better. but still could be prone to overload if a few jobs come in during that 10s.  I know @paulwe is working on a better scheme for this, but for now, wdyt about

* on the agent-side, when load metrics change, update immediately
* on the server-side, distribute probabilistically, inversely proportion to load

**Comment by real-danm** [comment]
that works for me, i'll refactor this and add a pr on the agent-side

**Comment by real-danm** [comment]
closing this out as there is some other refactoring work happening here

**Comment by real-danm** [comment]
added a few tests here. @paulwe for these unit tests, i short-circuited some of the simulated worker abilities to make sure they returned more quickly.

**Review by davidzhao — APPROVED** [review]
🫡

**Pull request merged**
