### PR TITLE
Return early if already subscribed.

### PR DESCRIPTION
**Pull request by boks1971**
When already subscribed, returned `subTrack` is nil. Return early, but do not return an error.

### CODE REVIEW

**Review by davidzhao — COMMENTED** [review]
we do not want to return if it's already subscribed.. since the rest of the process may not have ran successfully.

the previous logic did not return when the err was `errAlreadySubscribed`

**Review by davidzhao — COMMENTED** [review]
I guess we should change the logic from `AddSubscriber` to ensure it still returns the existing subscribed track? what do you think?

**Comment by boks1971** [comment]
> I guess we should change the logic from `AddSubscriber` to ensure it still returns the existing subscribed track? what do you think?

yeah and probably don't need to return an error either.

**Comment by boks1971** [comment]
> > I guess we should change the logic from `AddSubscriber` to ensure it still returns the existing subscribed track? what do you think?
> 
> yeah and probably don't need to return an error either.

Not sure about that. There are calls like `subTrack.AddOnBind` in that path (in the `OnTrackSubscribed` callback). That would end up adding an extra callback. Need to look at all the side effects. I think once it is subscribed, all the stuff is run. I do not see anything in the path where something fails and can be repaired. Maybe, I am reading it wrong. Need to look more carefully.

**Comment by davidzhao** [comment]
> 
> Not sure about that. There are calls like `subTrack.AddOnBind` in that path (in the `OnTrackSubscribed` callback). That would end up adding an extra callback. Need to look at all the side effects. I think once it is subscribed, all the stuff is run. I do not see anything in the path where something fails and can be repaired. Maybe, I am reading it wrong. Need to look more carefully.

ah yes.. AddOnBind changes the nature of this.. this is tricky.. I agree with you that this case is unlikely. but since the state is kept in two separate components.. they could diverge.

I guess another approach is to return (subTrack, errAlreadySubscribed), but then short circuit here so it doesn't add additional callbacks..

**Comment by boks1971** [comment]
> > Not sure about that. There are calls like `subTrack.AddOnBind` in that path (in the `OnTrackSubscribed` callback). That would end up adding an extra callback. Need to look at all the side effects. I think once it is subscribed, all the stuff is run. I do not see anything in the path where something fails and can be repaired. Maybe, I am reading it wrong. Need to look more carefully.
> 
> ah yes.. AddOnBind changes the nature of this.. this is tricky.. I agree with you that this case is unlikely. but since the state is kept in two separate components.. they could diverge.
> 
> I guess another approach is to return (subTrack, errAlreadySubscribed), but then short circuit here so it doesn't add additional callbacks..

yeah, that's an option. Will make a change to see how that looks.

**Comment by boks1971** [comment]
> > > Not sure about that. There are calls like `subTrack.AddOnBind` in that path (in the `OnTrackSubscribed` callback). That would end up adding an extra callback. Need to look at all the side effects. I think once it is subscribed, all the stuff is run. I do not see anything in the path where something fails and can be repaired. Maybe, I am reading it wrong. Need to look more carefully.
> > 
> > 
> > ah yes.. AddOnBind changes the nature of this.. this is tricky.. I agree with you that this case is unlikely. but since the state is kept in two separate components.. they could diverge.
> > I guess another approach is to return (subTrack, errAlreadySubscribed), but then short circuit here so it doesn't add additional callbacks..
> 
> yeah, that's an option. Will make a change to see how that looks.

Made the change in this [commit](https://github.com/livekit/livekit/pull/1377/commits/3136c787a635a950d50a1216a25969af73f8507f). Still returning `nil` if already subscribed from `AddSubscriber`, i. e. not changing that. But, checking for `!= nil` before invoking code that involves `subTrack`.

And to be safe (just in case `AddSubscriber` returns non-nil `subTrack` when already subscribed some day, also checking for `err == nil` in this [commit](https://github.com/livekit/livekit/pull/1377/commits/0ac23108a6bd22172de5e616055ee3ad8641aca5).

Please re-review when you get a chance.

**Review by davidzhao — APPROVED** [review]
I think this looks good.. though the situation is still not super clean.. if subscription.subscribedTrack remains nil, the reconciler will keep trying and running through this logic every 3s.. it will not be deemed "successful".

**Comment by boks1971** [comment]
> I think this looks good.. though the situation is still not super clean.. if subscription.subscribedTrack remains nil, the reconciler will keep trying and running through this logic every 3s.. it will not be deemed "successful".

This is only preventing a `nil` dereference when `AddSubscriber` returns a `nil` for `subTrack` when already subscribed. So, the initial subscription when `AddSubscriber` succeeded would have set the subscribed track to not nil, right?

This is only so that we do not panic on `nil` dereference and also run other bits of code like checking for first subscription to participant, etc.

**Pull request merged**
