### PR TITLE
Push Docker images to the master tag

### PR DESCRIPTION
**Pull request by dennwc**

### CODE REVIEW

**Comment by biglittlebigben** [comment]
Could you describe what this PR is solving?

**Comment by dennwc** [comment]
I need a Docker image of the latest LiveKit server for SIP to run tests in CI. But we don't want to release LK images without proper testing. So instead of tagging a release, this PR allows CI to release from `master` branch to `master` tag on the Docker Hub. This way SIP can pick up images from `master` tag without affecting the `latest` (which should still point to the last tagged release).

**Review by davidzhao — COMMENTED** [review]
Will this override `latest`? it seems that it would?

**Comment by dennwc** [comment]
@davidzhao I don't like this part either, because it's not obvious.

But according to [docs](https://github.com/docker/metadata-action?tab=readme-ov-file#latest-tag), by default the `latest` will be updated by 3 rule types:

- `type=ref,event=tag`
- `type=semver,pattern...`
- `type=match,pattern`

Which doesn't include the one added here (`type=ref,event=branch`).

All of the [examples](https://github.com/docker/metadata-action?tab=readme-ov-file#basic) also show that `master` can be enabled and it wouldn't update `latest` by default.

**Review by davidzhao — APPROVED** [review]

**Pull request merged**
