### PR TITLE
Cache and restore forwarder state on resume

### PR DESCRIPTION
**Pull request by boks1971**
This allows contiguous sequence number and VP8 picture ids.

TODO: Need to figure out if there is state saving needed with DD extension and what should be saved.

### CODE REVIEW

**Review by davidzhao — APPROVED** [review]
This is fantastic! Would AV1 use the VP8 path or RTP? Will we need to handle it differently there too?

**Comment by boks1971** [comment]
> This is fantastic! Would AV1 use the VP8 path or RTP? Will we need to handle it differently there too?

I do not know enough about the dependency descriptor extension. I need to understand what the implications there would be. I will file some issues to keep track.

**Comment by cnderrauber** [comment]
@boks1971  The resumed downtrack's dependency descriptor extension will be refresh by the key frame, so it don't need extra process.

**Comment by boks1971** [comment]
> @boks1971 The resumed downtrack's dependency descriptor extension will be refresh by the key frame, so it don't need extra process.

Awesome, thank you for looking at this and confirming @cnderrauber

**Pull request merged**
