### PR TITLE
Add support for Redis Sentinel

### PR DESCRIPTION
**Pull request by heilerich**
This adds support for Redis Sentinel, which provides automatic master-slave failover and is often used in clustered environments.

Let me know if you need more information :)

### CODE REVIEW

**Comment by jibon57** [comment]
@davidzhao will you please review this PR?

**Comment by bekriebel** [comment]
Just had a client run into this limitation. Could we get sentinel support added?

**Comment by bekriebel** [comment]
I've rebased this on to the current mainline in #707

**Comment by matkam** [comment]
Closing this PR as @bekriebel's branch has been merged.

**Pull request closed without merging**
