### PR TITLE
Prevent race of new track and new receiver.

### PR DESCRIPTION
**Pull request by boks1971**
Two different concepts
1. Creation of a new media track
2. Creation of a new receiver inside the media track

collided and caused track published to not be fired.

~~Unify to mark creation of new receiver as the source of truth. With simulcast codecs, creation of a new receiver should be treated as a new published track.~~ Changing it to fire `onTrackPublished` only on new track creation to keep current behaviour. Fixing it by firing it irrespective of new receiver or not.

### CODE REVIEW

**Review by cnderrauber — APPROVED** [review]
Good fix! This change will fire `trackPublished` twice in simulcast codec publishing while it was one `trackPublished` and one `trackUpdated` before, will it confuse the client and telemetry service?

**Comment by boks1971** [comment]
> Good fix! This change will fire `trackPublished` twice in simulcast codec publishing while it was one `trackPublished` and one `trackUpdated` before, will it confuse the client and telemetry service?

Good question @cnderrauber .  Ccing experts to understand better
cc: @shishirng for telemetry
cc: @lukasIO for clients

**Comment by boks1971** [comment]
> > Good fix! This change will fire `trackPublished` twice in simulcast codec publishing while it was one `trackPublished` and one `trackUpdated` before, will it confuse the client and telemetry service?
> 
> Good question @cnderrauber . Ccing experts to understand better cc: @shishirng for telemetry cc: @lukasIO for clients

Actually, I think I will revert to previous behaviour, i. e. fire `onTrackPublished` only on creation of a new track. Just have to put it outside the return value check of `AddReceiver`.

**Review by paulwe — APPROVED** [review]

**Review by davidzhao — COMMENTED** [review]
great catch Raja!

**Pull request merged**
