### PR TITLE
Update X's username in README.md

### PR DESCRIPTION
**Pull request by sonigeez**

### CODE REVIEW

**Comment by sonigeez** [comment]
hey apart from the PR, do you guys accept community contribution? if yes how can I join slack channel 
Thanks!

**Review by davidzhao — APPROVED** [review]
thanks!

**Comment by davidzhao** [comment]
You are welcome to join the slack community as well! https://livekit.io/join-slack

**Comment by sonigeez** [comment]
thanks for invitation @davidzhao but ig the slack community is restricted to livekit domains only
Screenshot 2023-10-01 at 11 55 06 AM

**Comment by dsa** [comment]
Thanks for reporting @sonigeez -- this link is fixed now. 🙏

**Pull request merged**
