### PR TITLE
add negotiate failed to ToDisconnectReason

### PR DESCRIPTION
**Pull request by cnderrauber**

### CODE REVIEW

**Review by boks1971 — APPROVED** [review]

**Review by boks1971 — COMMENTED** [review]
Probably need to add this field to the level protocol message also.

**Comment by cnderrauber** [comment]
@boks1971 what's the level protocol message? I probably not catch up with the disconnect reason change

**Comment by boks1971** [comment]
Leave has a reason, but it is set based on participant close reason in the close method. Can't remember if your change yesterday set it. Will check.

**Comment by boks1971** [comment]
Your change already hast it @cnderrauber . All good 👍

**Pull request merged**
