### PR TITLE
export ExtrackICEExtractICECredential for server-sdk-go

### PR DESCRIPTION
**Pull request by cnderrauber**
server-sdk-go need pending ice restart while ice gathering too.

### CODE REVIEW

**Review by boks1971 — APPROVED** [review]

**Comment by davidzhao** [comment]
should server-sdk-go depend on livekit-server? Ideally we are not pulling in this entire thing as a dependency.

**Comment by boks1971** [comment]
> should server-sdk-go depend on livekit-server? Ideally we are not pulling in this entire thing as a dependency.

ah, good point, skipped my mind. Should we make some utils module? Maybe, put it in `protocol` repo?

**Comment by cnderrauber** [comment]
> should server-sdk-go depend on livekit-server? Ideally we are not pulling in this entire thing as a dependency.

Just don't want copy code of this function to server-sdk-go, is there a good place for these common code?

**Comment by cnderrauber** [comment]
> > should server-sdk-go depend on livekit-server? Ideally we are not pulling in this entire thing as a dependency.
> 
> ah, good point, skipped my mind. Should we make some utils module? Maybe, put it in `protocol` repo?

I see, looks utils in protocol are all protocol related things, is it suitable for the sdp things.

**Comment by davidzhao** [comment]
> I see, looks utils in protocol are all protocol related things, is it suitable for the sdp things.

maybe moving sdp utils to `protocol/sdp` ?

**Comment by cnderrauber** [comment]
> > I see, looks utils in protocol are all protocol related things, is it suitable for the sdp things.
> 
> maybe moving sdp utils to `protocol/sdp` ?

In my mind, protocol is our application protocol, maybe is it not the best place, but better than this repo. anyhow, sdp is a `protocol` too :)

**Pull request closed without merging**
